apiVersion: apps/v1
kind: Deployment
metadata:
  name: estadisticas-service
  labels:
    app: estadisticas-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: estadisticas-service
  template:
    metadata:
      labels:
        app: estadisticas-service
    spec:
      containers:
        - name: estadisticas-service
          image: 152230379787.dkr.ecr.us-east-1.amazonaws.com/estadisticas-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006
              name: http
          envFrom:
            - secretRef:
                name: casino-secrets
          livenessProbe:
            httpGet:
              path: /livez
              port: 8006
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8006
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"